In [1]:
#how to open and save arrays

In [2]:
import numpy as np

In [3]:
arr = np.arange(5)

In [4]:
arr

array([0, 1, 2, 3, 4])

In [5]:
np.save ('myArray',arr)
#save

In [6]:
#to show it if its saved, craete an array with the same name

In [7]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
np.load('myArray.npy')
#call the saved file 

array([0, 1, 2, 3, 4])

In [9]:
#you can save multiple arrays
arr1 = np.load('myArray.npy')
arr1

array([0, 1, 2, 3, 4])

In [10]:
arr2 = arr

In [11]:
arr2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
np.savez('ziparray.npz',x=arr1, y=arr2)
#saving as file with 'savez'

In [13]:
#load multiple arrays
archive_array = np.load('ziparray.npz')

In [14]:
archive_array['x']

array([0, 1, 2, 3, 4])

In [15]:
archive_array['y']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
#make matrix
arr = np.array([[1,2,3],[4,5,6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [17]:
#save it as txt file
np.savetxt('myTextArray.txt',arr,delimiter=',') 

In [18]:
#load text file
arr = np.loadtxt('myTextArray.txt', delimiter=',')
arr

array([[1., 2., 3.],
       [4., 5., 6.]])