In [1]:
import numpy as np
import pandas as pd
from pandas import Series, DataFrame

In [2]:
arr1 = np.arange(9).reshape(3,3)

arr1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [3]:
#concatenate around axis 1 (in numpy)
np.concatenate([arr1,arr1],axis=1)

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [6, 7, 8, 6, 7, 8]])

In [4]:
#do it on different axis
np.concatenate([arr1,arr1],axis=0)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8],
       [0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [5]:
#how to do it in Pandas 
ser1 = Series([0,1,2], index=['T','U','V'])

ser2 = Series([3,4],index=['X','Y'])

In [6]:
ser1

T    0
U    1
V    2
dtype: int64

In [7]:
ser2

X    3
Y    4
dtype: int64

In [8]:
#concactenate in pandas
pd.concat([ser1,ser2])

T    0
U    1
V    2
X    3
Y    4
dtype: int64

In [9]:
#specify which axis - this makes it into dataframe
pd.concat([ser1,ser2],axis=1)

0    1
T  0.0  NaN
U  1.0  NaN
V  2.0  NaN
X  NaN  3.0
Y  NaN  4.0

In [10]:
#add markers by using herarchy
pd.concat([ser1,ser2], keys=['cat1','cat2'])


cat1  T    0
      U    1
      V    2
cat2  X    3
      Y    4
dtype: int64

In [11]:
#make dataframes
dFrame1 = DataFrame(np.random.randn(4,3),columns=['X','Y','Z'])

dFrame2 = DataFrame(np.random.randn(3,3),columns=['Y','Q','X'])


In [12]:
dFrame1

X         Y         Z
0  0.218990 -2.099056 -0.052105
1 -0.504830 -0.032420 -0.558526
2  1.513025  0.480873 -1.345030
3  0.648634 -1.180031  0.786108

In [13]:
dFrame2

Y         Q         X
0  1.265607  0.339991  1.724557
1  1.075512  0.637855 -1.829073
2 -0.395471 -0.880829  1.307570

In [14]:
pd.concat([dFrame1,dFrame2])

X         Y         Z         Q
0  0.218990 -2.099056 -0.052105       NaN
1 -0.504830 -0.032420 -0.558526       NaN
2  1.513025  0.480873 -1.345030       NaN
3  0.648634 -1.180031  0.786108       NaN
0  1.724557  1.265607       NaN  0.339991
1 -1.829073  1.075512       NaN  0.637855
2  1.307570 -0.395471       NaN -0.880829

In [16]:
pd.concat([dFrame1, dFrame2], ignore_index=True)

X         Y         Z         Q
0  0.218990 -2.099056 -0.052105       NaN
1 -0.504830 -0.032420 -0.558526       NaN
2  1.513025  0.480873 -1.345030       NaN
3  0.648634 -1.180031  0.786108       NaN
4  1.724557  1.265607       NaN  0.339991
5 -1.829073  1.075512       NaN  0.637855
6  1.307570 -0.395471       NaN -0.880829