In [1]:
import numpy as np

In [4]:
arr = np.arange(0,11)

In [5]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [6]:
arr[8]

8

In [8]:
arr[1:5]
#put a range from 1 to 5

array([1, 2, 3, 4])

In [9]:
#get values in range
arr[0:5]

array([0, 1, 2, 3, 4])

In [10]:
#set a value in range it sets them to a '100'
arr[0:5] = 100

In [11]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [12]:
arr = np.arange(0,11)

In [13]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [14]:
#slices of array
sliceOfArr = arr[0:6]

In [15]:
sliceOfArr

array([0, 1, 2, 3, 4, 5])

In [16]:
sliceOfArr[:] = 99
#set all values to be equal to 99. changes apply on original array 

In [18]:
sliceOfArr

array([99, 99, 99, 99, 99, 99])

In [19]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [21]:
arrCopy = arr.copy()
#to create explicit copy

In [23]:
arrCopy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [24]:
arr2d = np.array([[5,10,15],[20,25,30],[30,40,45]])

In [25]:
arr2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [30, 40, 45]])

In [26]:
arr2d[1]
#index starts at 0, show us the valeus from row

array([20, 25, 30])

In [27]:
arr2d[2][0]
#row and index column

30

In [28]:
arr2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [30, 40, 45]])

In [29]:
arr2d[:2,1:]
#asking for 1 column index and ecerything until the second index row 

array([[10, 15],
       [25, 30]])

In [30]:
arr2d[2]

array([30, 40, 45])

In [33]:
#fancy indexing 
arr_2d = np.zeros((10,10))

In [34]:
arr_2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [35]:
arr_lenght = arr_2d.shape[1]

In [36]:
arr_lenght

10

In [48]:
for i in range(arr_lenght):
    arr_2d[i]=i

In [49]:
arr_2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.]])

In [51]:
arr_2d[[2,4,6,8]]
#fancy indexing

array([[2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.]])

In [52]:
arr_2d[[6,4,2,7]]

array([[6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.]])

In [45]:
arr_2d

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])