In [1]:
import numpy as np 
import pandas as pd
from pandas import Series, DataFrame

In [3]:
#reorder series or dataframe and reordering as permutation
#create dataframe
dFrame = DataFrame(np.arange(16).reshape((4,4)))
dFrame

0   1   2   3
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15

In [4]:
#create array with random permutation
#permutation of the numbers 0,1,2,3
blender = np.random.permutation(4)

In [5]:
blender

array([2, 3, 1, 0])

In [6]:
#use the take method to create permutation
#from dataframe take index 0,1,2,34 and put them in the order of blender 
dFrame.take(blender)

0   1   2   3
2   8   9  10  11
3  12  13  14  15
1   4   5   6   7
0   0   1   2   3

In [7]:
#what if you want to do permutations with replacement
#create object of box
box = np.array([1,2,3])

In [8]:
#create new object
#randint is premutation with replacement
shaker = np.random.randint(0,len(box),size=10)

In [9]:
shaker

array([1, 0, 0, 1, 0, 2, 1, 2, 2, 0])

In [10]:
#new object
hand_grabs = box.take(shaker)

In [11]:
hand_grabs

array([2, 1, 1, 2, 1, 3, 2, 3, 3, 1])