In [1]:
import numpy as np

In [4]:
arr = np.arange(11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [5]:
#square root
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [6]:
np.exp(arr)
#exponision

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [8]:
#binary functions, call random standart distribution
A = np.random.randn(10)
A

array([ 2.32769264, -0.89098485, -0.08415283, -1.15075905,  0.49650346,
       -1.37239831, -1.31720045, -1.26457012, -0.65991294, -0.57178815])

In [10]:
B = np.random.randn(10)
B

array([-0.724564  , -0.47848079, -0.16158663,  1.24630252,  0.3991509 ,
       -0.11705181, -1.0023564 ,  1.00862845,  0.66244389, -1.44869138])

In [11]:
#Binary functions
np.add(A,B)

array([ 1.60312863, -1.36946564, -0.24573946,  0.09554347,  0.89565436,
       -1.48945012, -2.31955685, -0.25594167,  0.00253096, -2.02047953])

In [12]:
#find max or min
np.maximum(A,B)

array([ 2.32769264, -0.47848079, -0.08415283,  1.24630252,  0.49650346,
       -0.11705181, -1.0023564 ,  1.00862845,  0.66244389, -0.57178815])

In [16]:
website = ‚
import webbrowser
webbrowser.open(website)

NameError: name 'url' is not defined